Repository ONSdigital/ssdc-rm-acceptance-tests, pull requests merged in 2022-10, with the labels that each got.

#128 Fail tests when messages remain on topics
  acceptance_tests/features/SupportTool_UI.feature
  acceptance_tests/features/environment.py
  acceptance_tests/features/steps/supporttool_ui.py
  acceptance_tests/features/telephone_capture.feature
  acceptance_tests/utilities/pubsub_helper.py
Labels: patch

#135 Add prototype PHM feature
  Pipfile
  Pipfile.lock
  acceptance_tests/features/PHM.feature
  acceptance_tests/utilities/file_to_process_upload_helper.py
  resources/sample_files/PHM_prototype_dummy_sample.csv
  resources/validation_rules/PHM_prototype_validation_rules.json
  resources/validation_rules/email_driven_rules.json
Labels: feature

#137 make one test work for both en & cy
  acceptance_tests/features/RH_UI.feature
  acceptance_tests/features/steps/rh_endpoint.py
  acceptance_tests/features/steps/rh_ui.py
  acceptance_tests/utilities/jwe_helper.py
  acceptance_tests/utilities/rh_endpoint_client.py
  acceptance_tests/utilities/rh_helper.py
Labels: feature

#139 Update RH_UI.feature
  acceptance_tests/features/RH_UI.feature
Labels: bug, patch

#138 Update jwe_helper.py
  acceptance_tests/utilities/jwe_helper.py
Labels: feature
