Repository ONSdigital/ssdc-rm-acceptance-tests, pull requests merged in 2022-08, with the labels that each got.

#114 284 Use commit ref image tag
  .gitignore
  README.md
  acceptance_tests_pod.yml
  run_gke.sh
  tasks/kubectl-run-acceptance-tests.yml
Labels: patch

#115 284 Fix concourse task manifest path
  tasks/kubectl-run-acceptance-tests.yml
Labels: patch

#117 alter tests to work with new eq claims
  acceptance_tests/features/RH_UI.feature
  acceptance_tests/features/steps/events_emitted.py
  acceptance_tests/features/steps/rh_endpoint.py
  acceptance_tests/features/steps/rh_ui.py
  acceptance_tests/utilities/jwe_helper.py
  resources/dummy_keys/dummy_eq_token_decryption_key.pem
  resources/dummy_keys/dummy_eq_token_verification_key.pem
Labels: breaking change

#118 298 Fix tests not consuming launch UAC update
  acceptance_tests/features/RH_UI.feature
  acceptance_tests/features/steps/rh_ui.py
Labels: patch

#120 Fix Travis check
  .travis.yml
Labels: patch

#121 164 support tool tests key features only
  acceptance_tests/features/SupportTool_UI.feature
  acceptance_tests/features/environment.py
  acceptance_tests/features/steps/sample_loading.py
  acceptance_tests/features/steps/supporttool_ui.py
  acceptance_tests_pod.yml
  config.py
Labels: feature
