Repository ONSdigital/ssdc-rm-acceptance-tests, pull requests merged in 2022-11, with the labels that each got.

#140 fixes for support tool ui tests, had failed a couple of times. Also updated Pip lock for wheel
  Makefile
  Pipfile.lock
  acceptance_tests/features/steps/supporttool_ui.py
Labels: bug, patch

#141 Update UI test for Welsh translation
  acceptance_tests/features/RH_UI.feature
Labels: patch

#142 update ATs for new inactive UAC page
  acceptance_tests/features/steps/rh_ui.py
Labels: feature
